name = opw_fixes
optional_depends = travelnet, areas, replacer, techage, x_bows, x_bows_extras, blazing_tools, toolranks, twchests, darkage, unifieddyes, colorcubes, default, exoticores, xdecor, industrious, screwdriver, amethyst_new, farmtools, basic_materials, stairs, industrialtest, technic, cucina_vegana, binoculars, ethereal
  
