name = opw_fixes
optional_depends = darkage, unifieddyes, colorcubes, default, exoticores, xdecor, industrious, screwdriver, amethyst_new, farmtools, basic_materials, stairs, industrialtest, technic, cucina_vegana, ethereal
  
